### ISSUE TITLE
Upgrade codebase to use Next version 13

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/classroom#449]
**Describe the feature**
Currently, the project uses Next version 12.  We would like to upgrade to Next version 13

**Background info**
As a starting point, 
1. Go to package.json
2. Note that next version is pinned to ^12.1.6.  We should upgrade to version 13. 
3. Next.js provided a [guide](https://nextjs.org/docs/pages/building-your-application/upgrading/version-13) for migrating from version 12 to version 13.  Please read this carefully. 

**Additional context**

- You may also need to upgrade related libraries / frameworks.  For example, next-auth may need to get upgraded to a higher version.  Node.js may need to get upgraded to a higher version.  
- Changing so many core frameworks may have adverse effects on the functionality of the project.  Please test thoroughly to make sure that the application still works and all the pages correctly.  
- Note that after you change the package.json, you will need to run **npm install** again in order to regenerate the package-lock.json file.

**Comment by lloydchang** [comment]
For future readers:

> For example, next-auth may need to get upgraded to a higher version.

Regarding next-auth:

It relates to
https://github.com/freeCodeCamp/classroom/pull/447
https://github.com/freeCodeCamp/classroom/actions/runs/5840184831/job/15839146689?pr=447
https://github.com/freeCodeCamp/classroom/actions/runs/5840185087/job/15839147138#step:6:56

Note: Mend Renovate bot's attempt at:
> fix(deps): update dependency next-auth to v4.23.0

> `"next-auth": "4.22.4",` -> `"next-auth": "4.23.0",`

resulted in an error when running tests via CI.

For example:
> [ⓧ Build and test (16.14.2)](https://github.com/freeCodeCamp/classroom/actions/runs/5840185087/job/15839147138#step:6:56)
Process completed with exit code 1.
<details><summary>Details</summary>
<b>Run tests 4s</b>
<pre>
Run npm run test
  npm run test
  shell: /usr/bin/bash -e {0}

> @freecodecamp/classroom@0.0.0 test
> jest .

PASS __tests__/components/updateUserForm.test.jsx
PASS __tests__/components/adminTable.test.jsx
FAIL __tests__/components/authButton.test.jsx
  ● Test suite failed to run

    Cannot find module 'next-auth/react' from '__tests__/components/authButton.test.jsx'

      4 | import { useSession } from 'next-auth/react';
      5 |
    > 6 | jest.mock('next-auth/react', () => {
        |      ^
      7 |   const originalModule = jest.requireActual('next-auth/react');
      8 |   return {
      9 |     __esModule: true,

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:4[2](https://github.com/freeCodeCamp/classroom/actions/runs/5840184831/job/15839146689?pr=447#step:6:2)7:11)
      at Object.mock (__tests__/components/authButton.test.jsx:6:6)

PASS __tests__/components/dashtable_v2.test.jsx
FAIL __tests__/components/navbar.test.jsx
  ● Test suite failed to run

    Cannot find module 'next-auth/react' from 'components/authButton.js'

    Require stack:
      components/authButton.js
      components/navbar.js
      __tests__/components/navbar.test.jsx

       8 |         <button
       9 |           onClick={() => signOut()}
    > 10 |           className='hover:bg-[#ffbf00] shadow-lg border-solid border-color: inherit; border-[1px] pl-4 pr-4 bg-fcc-primary-yellow text-black'
         |                ^
      11 |         >
      12 |           Sign out
      1[3](https://github.com/freeCodeCamp/classroom/actions/runs/5840184831/job/15839146689?pr=447#step:6:3) |         </button>

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:[4](https://github.com/freeCodeCamp/classroom/actions/runs/5840184831/job/15839146689?pr=447#step:6:5)27:11)
      at Object.<anonymous> (components/authButton.js:10:16)
      at Object.<anonymous> (components/navbar.js:13:[5](https://github.com/freeCodeCamp/classroom/actions/runs/5840184831/job/15839146689?pr=447#step:6:6)8)
      at Object.<anonymous> (__tests__/components/navbar.test.jsx:[6](https://github.com/freeCodeCamp/classroom/actions/runs/5840184831/job/15839146689?pr=447#step:6:7):54)

Test Suites: 2 failed, 3 passed, 5 total
Tests:       5 passed, 5 total
Snapshots:   5 passed, 5 total
Time:        2.[7](https://github.com/freeCodeCamp/classroom/actions/runs/5840184831/job/15839146689?pr=447#step:6:8)[9](https://github.com/freeCodeCamp/classroom/actions/runs/5840184831/job/15839146689?pr=447#step:6:10)7 s
Ran all test suites matching /./i.
Error: Process completed with exit code 1.
</pre>

<b>Run tests 2s</b>
<pre>
Run npm run test
  npm run test
  shell: /usr/bin/bash -e {0}

> @freecodecamp/classroom@0.0.0 test
> jest .

PASS __tests__/components/updateUserForm.test.jsx
PASS __tests__/components/adminTable.test.jsx
FAIL __tests__/components/authButton.test.jsx
  ● Test suite failed to run

    Cannot find module 'next-auth/react' from '__tests__/components/authButton.test.jsx'

      4 | import { useSession } from 'next-auth/react';
      5 |
    > 6 | jest.mock('next-auth/react', () => {
        |      ^
      7 |   const originalModule = jest.requireActual('next-auth/react');
      8 |   return {
      9 |     __esModule: true,

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:4[2](https://github.com/freeCodeCamp/classroom/actions/runs/5840185087/job/15839147138#step:6:2)7:11)
      at Object.mock (__tests__/components/authButton.test.jsx:6:6)

PASS __tests__/components/dashtable_v2.test.jsx
FAIL __tests__/components/navbar.test.jsx
  ● Test suite failed to run

    Cannot find module 'next-auth/react' from 'components/authButton.js'

    Require stack:
      components/authButton.js
      components/navbar.js
      __tests__/components/navbar.test.jsx

       8 |         <button
       9 |           onClick={() => signOut()}
    > 10 |           className='hover:bg-[#ffbf00] shadow-lg border-solid border-color: inherit; border-[1px] pl-4 pr-4 bg-fcc-primary-yellow text-black'
         |                ^
      11 |         >
      12 |           Sign out
      1[3](https://github.com/freeCodeCamp/classroom/actions/runs/5840185087/job/15839147138#step:6:3) |         </button>

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:[4](https://github.com/freeCodeCamp/classroom/actions/runs/5840185087/job/15839147138#step:6:5)27:11)
      at Object.<anonymous> (components/authButton.js:10:16)
      at Object.<anonymous> (components/navbar.js:13:[5](https://github.com/freeCodeCamp/classroom/actions/runs/5840185087/job/15839147138#step:6:6)8)
      at Object.<anonymous> (__tests__/components/navbar.test.jsx:[6](https://github.com/freeCodeCamp/classroom/actions/runs/5840185087/job/15839147138#step:6:7):54)

Test Suites: 2 failed, 3 passed, 5 total
Tests:       5 passed, 5 total
Snapshots:   5 passed, 5 total
Time:        1.[7](https://github.com/freeCodeCamp/classroom/actions/runs/5840185087/job/15839147138#step:6:8)9[8](https://github.com/freeCodeCamp/classroom/actions/runs/5840185087/job/15839147138#step:6:9) s
Ran all test suites matching /./i.
Error: Process completed with exit code 1.
</pre>
</details>

**Comment by utsab** [comment]
We may revisit this in the future
